### ISSUE TITLE
Pass additional data to the called function?

### ISSUE THREAD

**Issue by slavafomin** [rpocklin/angular-scroll-animate#8]
Hello!

Is there a way to pass some additional data to the called function?

E.g.: `when-visible="animate('slide-left')"`.

**Comment by rpocklin** [comment]
Best bet is to create a function for `when-visible` that calls any functions you need with any parameters you require.

**Comment by slavafomin** [comment]
I have a very big landing page with animations that needs to be applied to different elements, when they become visible. It will be a total waste to create wrapping functions for each combination of applied CSS classes. I'm looking for a way to control this from view perspective.

**Comment by rpocklin** [comment]
So are you using `ng-repeat` to show these elements?  It's possible to do, just not using `&` in the directive as it currently is.

**Comment by slavafomin** [comment]
I'm pretty sure Angular allows to execute an arbitrary expressions passed to a directive using `&` scope property definition. However, it looks like your module enforces us to pass a function directly to it instead of an arbitrary expression. I'm not sure, why are you limiting the functionality this way?

I think the problem is here: https://github.com/rpocklin/angular-scroll-animate/blob/master/src/angular-scroll-animate.js#L136.

If you allow us to pass an arbitrary expression my example above should work. I think the author of #7 also experienced the depicted problem, he passed not a function, but an expression.

**Comment by rpocklin** [comment]
I didn't purposefully set out to make this hard for you.  It's a limitation of using `&` with angular, not this directive!

You are the first person to mention it, it's always possible you are using it differently to most others.

I'll look at it over the next few days.

**Comment by slavafomin** [comment]
Thanks Robert, I understand ))

However, I think there should be a way to make it more flexible, I will also look into it.

**Comment by slavafomin** [comment]
Please look at this very simplified example:
https://plnkr.co/edit/L27HCY08ADiPpUXstNDP?p=preview

As you can see, the directive could pretty easily evaluate complex expressions passed to it.

If you could implement this for `whenVisible` property it would be awesome ;)

**Comment by rpocklin** [comment]
Best way to achieve this (augmented code from included repo example):

``` javascript
    $scope.animateElementIn = function(animationClass) {
        return function($el) {
            $el.removeClass('not-visible');
            $el.addClass('animated ' + animationClass;
        };
    };
```

``` html
    <div ng-repeat="car in cars" when-visible="animateElementIn('fadeInLeft')" when-not-visible="animateElementOut" class="not-visible car-container">
```

This allows you to pass custom data in (either static values, or something based on the repeated `car`, and you still keep the same API for the directive.

**Comment by slavafomin** [comment]
Hello @rpocklin!

That looks exactly that I was asking for. Have you updated the directive's code?

I'm not ready to test it out for now, however, I will return to this in the future probably. Thank you!

**Comment by rpocklin** [comment]
No source code was changed, that code will work with the existing published directive.
If you want to +1 on #9 that might be something you are after (ie. if the classes can be dynamic, defined on each element within an `ng-repeat`.
